### PR TITLE
This is a pull request to update rnn to the latests changes on main

### PR DESCRIPTION
**Pull request by luisaforozco**

### CODE REVIEW

**Comment by luisaforozco** [comment]
I cannot merge because I would need to commit on main. This is because

**Comment by chyalexcheng** [comment]
seems like we only need to resolve the conflicts in pyproject.toml. I understood you did that as well. The RNN branch and the docu look quite good. Is the rnn branch ready to be merged?

**Comment by luisaforozco** [comment]
Branch rnn is not ready to merge yet, but is very clear for me how to solve the conflict. I will take care of that when the PR will take place.

**Comment by luisaforozco** [comment]
The non-succesfull checks is due to conftest.py that requires package h5py. I have made the required changes on pyproject.toml in rnn branch.

**Pull request merged**
