### PR TITLE
Poetry extras

### PR DESCRIPTION
**Pull request by luisaforozco**
This PR includes changes to:
- **README.md**: adding badges, adjusting the table, deleting running the test ins installation instructions
- **README.dev.md**: Instructions to install the package for developer (docs and dev options)
- **pyproject.toml** : Deleted the groups and work now with extras. This allows more flexibility and less confusion about dependencies that are not necessary for every type of user. I left matplotlib in the main dependencies because it is necessary to run the examples.
- **github actions**: modified the commands to install the packages so that the good dependencies will be installed in the docker images that are run during the CI/CD and docs generation (readthedocs). 

I have checked both installation methods: poetry and pip, in 2 different platforms: macOS and linux (Snellius). 

@chyalexcheng Could you please take a look, maybe even test it - I don't have access to a windows machine-, and if everything is ok approve the pull request? 
Of course, wait until all CI/CD are passing.
Thanks.

### CODE REVIEW

**Review by chyalexcheng — APPROVED** [review]

**Review by chyalexcheng — APPROVED** [review]
-E or --extras which way is more explicit?

**Review by chyalexcheng — APPROVED** [review]

**Review by chyalexcheng — APPROVED** [review]
which IDE do you use? I use PyCharm. It reformats files from time to time.

**Review by chyalexcheng — APPROVED** [review]

**Review by chyalexcheng — COMMENTED** [review]
why not run the test to see if GL is installed correctly?

**Review by chyalexcheng — APPROVED** [review]
Thank you for fixing this.

**Comment by luisaforozco** [comment]
So, now is working. There are some changes that need to be done, but I prefer that @chyalexcheng  check at them (is more about the content).
I created issue #18 to work on improving the paths. With this changes the merge is ready, if you agree Hongyang.

**Pull request merged**
